Repository SC-ECE/POSTER-DESIGNING, pull requests merged in 2023-01, with the labels that each got.

#4 Created women's day poster
  Women's Day Poster/Image/8th March.png
  Women's Day Poster/Image/Soumyajit.png
  Women's Day Poster/README.md
Labels: Easy, Synapse

#5 World Environment Day poster
  World environment day/README.md
  World environment day/World Environment Day.jpg
Labels: Easy, Synapse

#7 Synapse poster
  Synapse poster/Arnab.png
  Synapse poster/README.md
  Synapse poster/sYNAPSE poster 1.0.jpg
Labels: Easy, Synapse

#6 Internship Poster
  Internship poster/Readme.md
  Internship poster/poster 1.jpg
Labels: Synapse

#8 Mother's Day Poster
  Mothers Day Poster/Mothers' Day Poster.png
  Mothers Day Poster/README.md
Labels: Medium, Synapse

#9 World Health Day Poster
  World Health Day Poster/Readme.md
  World Health Day Poster/world Health Day poster.png
Labels: Easy, Synapse

#10 International Childhood Cancer Day Poster
  International childhood cancer day Poster/International Children Cancer Day Poster.png
  International childhood cancer day Poster/README.md
Labels: Easy, Synapse

#12 23 Rd January Poster
  23rd January/23rd Jan Poster.png
  23rd January/README.md
Labels: Medium, Synapse

#13 World Wildlife Day Poster
  World Wildlife day poster/README.md
  World Wildlife day poster/wildlife.png
Labels: Medium, Synapse

#14 National Vaccination Day Poster
  National Vaccination Day poster/National vaccination day poster.png
  National Vaccination Day poster/README.md
Labels: Medium, Synapse

#18 National Youth Day poster
  National Youth Day poster/National Youth Day Poster.png
  National Youth Day poster/README.md
Labels: Easy, Synapse

#20 World Earth Day
  World Earth Day poster/README.md
  World Earth Day poster/World Earth Day Poster.png
Labels: Easy, Synapse

#25 #Wedding Invitation
  Wedding Invitation/README.md
  Wedding Invitation/wedding_invitation.png
Labels: Medium, Synapse

#26 International Mother language day poster
  International Mother language day poster/International Mother Language Day.png
  International Mother language day poster/README.md
Labels: Medium, Synapse

#27 Poster For Mother's Day
  Poster for Mothers Day/Mothers Day Poster.png
  Poster for Mothers Day/README.md
Labels: Medium, Synapse

#28 World AIDS day poster
  World Aids Day poster/README.md
  World Aids Day poster/World Aids Day.png
Labels: Medium, Synapse
