Repository SC-ECE/POSTER-DESIGNING, pull requests merged in 2023-02, with the labels that each got.

#31 LABOUR DAY
  README.md
  may de.png
Labels: Medium, Synapse

#34 TEACHERS DAY
  README.md
  TEACHERS DAY.png
Labels: Easy, Synapse

#35 World dance day
  World dance day poster/world dance day poster.png
Labels: Medium, Easy, Synapse
